import {
  GPU_IMAGE_CACHE_DEFAULT_BYTES, GPU_IMAGE_CACHE_HARD_MAX_BYTES,
  GPU_UPLOAD_MAX_BYTES_PER_FRAME, GPU_UPLOAD_MAX_ITEMS_PER_FRAME, GPU_UPLOAD_MAX_MS_PER_FRAME,
} from '../../shared/imagePipelineConfig';

export const CANVAS_MIP_EDGES = [128, 256, 512, 1024, 2048, 4096] as const;
export const CANVAS_MIP_OVERSAMPLE = 1.25;
export const PREFETCH_VIEWPORT_MARGIN = 0.75;
export const GPU_TEXTURE_BUDGET_BYTES = Math.min(GPU_IMAGE_CACHE_DEFAULT_BYTES, GPU_IMAGE_CACHE_HARD_MAX_BYTES);
export const GPU_UPLOAD_BUDGET = {
  items: GPU_UPLOAD_MAX_ITEMS_PER_FRAME,
  bytes: GPU_UPLOAD_MAX_BYTES_PER_FRAME,
  milliseconds: GPU_UPLOAD_MAX_MS_PER_FRAME,
} as const;
