use std::{
    collections::HashMap,
    sync::{
        atomic::{AtomicBool, AtomicU64, Ordering},
        mpsc, Arc,
    },
    thread,
};

use parking_lot::Mutex;

type JobTask = Box<dyn FnOnce(Arc<AtomicBool>) -> Result<Vec<u8>, String> + Send + 'static>;
type Waiter = mpsc::Sender<Result<Vec<u8>, String>>;

struct Job {
    key: String,
    priority: i32,
    sequence: u64,
    canceled: Arc<AtomicBool>,
    task: Option<JobTask>,
    waiters: Vec<Waiter>,
}

struct QueueState {
    pending: Vec<Job>,
    inflight: HashMap<String, InflightMeta>,
    active: usize,
    sequence: u64,
}

struct InflightMeta {
    priority: i32,
    canceled: Arc<AtomicBool>,
    running: bool,
    sequence: u64,
    /// Waiters attached after the job already left `pending` (running).
    waiters: Vec<Waiter>,
}

#[derive(Clone, Debug, Default)]
pub struct ImageJobStats {
    pub active: usize,
    pub pending: usize,
    pub inflight: usize,
    pub concurrency: usize,
}

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct ImageJobStatus {
    pub running: bool,
    pub queue_position: Option<usize>,
}

pub struct ImageJobQueue {
    state: Arc<Mutex<QueueState>>,
    concurrency: usize,
    completed: AtomicU64,
}

impl std::fmt::Debug for ImageJobQueue {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.debug_struct("ImageJobQueue").field("concurrency", &self.concurrency).finish()
    }
}

impl ImageJobQueue {
    pub fn new(concurrency: usize) -> Arc<Self> {
        Arc::new(Self {
            state: Arc::new(Mutex::new(QueueState {
                pending: Vec::new(),
                inflight: HashMap::new(),
                active: 0,
                sequence: 0,
            })),
            concurrency: concurrency.max(1),
            completed: AtomicU64::new(0),
        })
    }

    /// Enqueue work and return a receiver for the generated bytes.
    /// Callers for the same key share one single-flight job.
    pub fn enqueue(
        self: &Arc<Self>,
        key: String,
        priority: i32,
        task: impl FnOnce(Arc<AtomicBool>) -> Result<Vec<u8>, String> + Send + 'static,
    ) -> mpsc::Receiver<Result<Vec<u8>, String>> {
        let (sender, receiver) = mpsc::channel();
        {
            let mut state = self.state.lock();
            let join_existing = state.inflight.get(&key).and_then(|existing| {
                (!existing.canceled.load(Ordering::SeqCst)).then_some(existing.sequence)
            });
            if let Some(sequence) = join_existing {
                if let Some(meta) = state.inflight.get_mut(&key) {
                    meta.priority = meta.priority.max(priority);
                }
                if let Some(job) = state.pending.iter_mut().find(|job| job.sequence == sequence) {
                    job.priority = job.priority.max(priority);
                    job.waiters.push(sender);
                } else if let Some(meta) = state.inflight.get_mut(&key) {
                    meta.waiters.push(sender);
                }
                drop(state);
                self.pump();
                return receiver;
            }
            state.sequence += 1;
            let sequence = state.sequence;
            let canceled = Arc::new(AtomicBool::new(false));
            state.inflight.insert(key.clone(), InflightMeta {
                priority,
                canceled: canceled.clone(),
                running: false,
                sequence,
                waiters: Vec::new(),
            });
            state.pending.push(Job {
                key,
                priority,
                sequence,
                canceled,
                task: Some(Box::new(task)),
                waiters: vec![sender],
            });
        }
        self.pump();
        receiver
    }

    pub fn boost(self: &Arc<Self>, mut predicate: impl FnMut(&str) -> bool, priority: i32) -> usize {
        let mut promoted = 0;
        {
            let mut state = self.state.lock();
            for (key, meta) in state.inflight.iter_mut() {
                if meta.canceled.load(Ordering::SeqCst) || !predicate(key) || priority <= meta.priority {
                    continue;
                }
                meta.priority = priority;
                promoted += 1;
            }
            for job in &mut state.pending {
                if job.canceled.load(Ordering::SeqCst) || !predicate(&job.key) || priority <= job.priority {
                    continue;
                }
                job.priority = priority;
            }
        }
        if promoted > 0 { self.pump(); }
        promoted
    }

    pub fn cancel(&self, mut predicate: impl FnMut(&str) -> bool) -> usize {
        let mut canceled = 0;
        let mut orphan_waiters = Vec::new();
        let mut state = self.state.lock();
        let keys = state.inflight.keys().cloned().collect::<Vec<_>>();
        for key in keys {
            if !predicate(&key) { continue; }
            if let Some(meta) = state.inflight.get_mut(&key) {
                if meta.canceled.swap(true, Ordering::SeqCst) { continue; }
                canceled += 1;
                orphan_waiters.append(&mut meta.waiters);
                if !meta.running {
                    state.inflight.remove(&key);
                }
            }
        }
        state.pending.retain_mut(|job| {
            if !job.canceled.load(Ordering::SeqCst) {
                return true;
            }
            orphan_waiters.append(&mut job.waiters);
            false
        });
        drop(state);
        for waiter in orphan_waiters {
            let _ = waiter.send(Err("图像任务已取消".into()));
        }
        canceled
    }

    pub fn stats(&self) -> ImageJobStats {
        let state = self.state.lock();
        ImageJobStats {
            active: state.active,
            pending: state.pending.iter().filter(|job| !job.canceled.load(Ordering::SeqCst)).count(),
            inflight: state.inflight.len(),
            concurrency: self.concurrency,
        }
    }

    pub fn job_status(&self, key: &str) -> Option<ImageJobStatus> {
        let state = self.state.lock();
        let meta = state.inflight.get(key)?;
        if meta.running {
            return Some(ImageJobStatus { running: true, queue_position: None });
        }
        let mut pending = state.pending.iter()
            .filter(|job| !job.canceled.load(Ordering::SeqCst))
            .collect::<Vec<_>>();
        pending.sort_by(|left, right| {
            right.priority.cmp(&left.priority).then(left.sequence.cmp(&right.sequence))
        });
        let position = pending.iter().position(|job| job.key == key).map(|index| index + 1);
        Some(ImageJobStatus { running: false, queue_position: position })
    }

    pub fn completed(&self) -> u64 { self.completed.load(Ordering::Relaxed) }

    fn pump(self: &Arc<Self>) {
        loop {
            let next = {
                let mut state = self.state.lock();
                if state.active >= self.concurrency { return; }
                state.pending.sort_by(|left, right| {
                    right.priority.cmp(&left.priority).then(left.sequence.cmp(&right.sequence))
                });
                let Some(index) = state.pending.iter().position(|job| !job.canceled.load(Ordering::SeqCst)) else {
                    return;
                };
                let mut job = state.pending.remove(index);
                if let Some(meta) = state.inflight.get_mut(&job.key) {
                    meta.running = true;
                    meta.priority = job.priority;
                    job.waiters.append(&mut meta.waiters);
                }
                state.active += 1;
                let task = job.task.take();
                Some((job.key, job.sequence, job.canceled, job.waiters, task))
            };
            let Some((key, sequence, canceled, waiters, Some(task))) = next else { return; };
            let queue = Arc::clone(self);
            thread::spawn(move || {
                let result = if canceled.load(Ordering::SeqCst) {
                    Err("图像任务已取消".into())
                } else {
                    task(canceled.clone())
                };
                notify_waiters(&waiters, &result);
                queue.completed.fetch_add(1, Ordering::Relaxed);
                {
                    let mut state = queue.state.lock();
                    state.active = state.active.saturating_sub(1);
                    if state.inflight.get(&key).is_some_and(|meta| meta.sequence == sequence) {
                        if let Some(meta) = state.inflight.remove(&key) {
                            notify_waiters(&meta.waiters, &result);
                        }
                    }
                }
                queue.pump();
            });
        }
    }
}

fn notify_waiters(waiters: &[Waiter], result: &Result<Vec<u8>, String>) {
    for waiter in waiters {
        let payload = match result {
            Ok(bytes) => Ok(bytes.clone()),
            Err(error) => Err(error.clone()),
        };
        let _ = waiter.send(payload);
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::{sync::atomic::AtomicUsize, time::Duration};

    #[test]
    fn single_worker_queue_never_runs_two_proxy_jobs_at_once() {
        let queue = ImageJobQueue::new(1);
        let active = Arc::new(AtomicUsize::new(0));
        let peak = Arc::new(AtomicUsize::new(0));
        let make_task = || {
            let active = active.clone();
            let peak = peak.clone();
            move |_canceled: Arc<AtomicBool>| {
                let current = active.fetch_add(1, Ordering::SeqCst) + 1;
                peak.fetch_max(current, Ordering::SeqCst);
                thread::sleep(Duration::from_millis(20));
                active.fetch_sub(1, Ordering::SeqCst);
                Ok(Vec::new())
            }
        };
        let first = queue.enqueue("video-proxy:first".into(), 1, make_task());
        let second = queue.enqueue("video-proxy:second".into(), 2, make_task());
        assert!(first.recv_timeout(Duration::from_secs(2)).expect("first").is_ok());
        assert!(second.recv_timeout(Duration::from_secs(2)).expect("second").is_ok());
        assert_eq!(peak.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn shared_proxy_asset_uses_one_single_flight_job() {
        let queue = ImageJobQueue::new(1);
        let executions = Arc::new(AtomicUsize::new(0));
        let (started_sender, started_receiver) = mpsc::channel();
        let (release_sender, release_receiver) = mpsc::channel();
        let first_executions = executions.clone();
        let first = queue.enqueue("video-proxy:shared".into(), 1, move |_canceled| {
            first_executions.fetch_add(1, Ordering::SeqCst);
            let _ = started_sender.send(());
            let _ = release_receiver.recv_timeout(Duration::from_secs(2));
            Ok(vec![7])
        });
        started_receiver.recv_timeout(Duration::from_secs(2)).expect("started");
        let joined_executions = executions.clone();
        let joined = queue.enqueue("video-proxy:shared".into(), 9, move |_canceled| {
            joined_executions.fetch_add(1, Ordering::SeqCst);
            Ok(vec![9])
        });
        let _ = release_sender.send(());
        assert_eq!(first.recv_timeout(Duration::from_secs(2)).expect("first"), Ok(vec![7]));
        assert_eq!(joined.recv_timeout(Duration::from_secs(2)).expect("joined"), Ok(vec![7]));
        assert_eq!(executions.load(Ordering::SeqCst), 1);
    }

    #[test]
    fn cancel_removes_a_queued_proxy_job() {
        let queue = ImageJobQueue::new(1);
        let (release_sender, release_receiver) = mpsc::channel();
        let active = queue.enqueue("video-proxy:active".into(), 1, move |_canceled| {
            let _ = release_receiver.recv_timeout(Duration::from_secs(2));
            Ok(Vec::new())
        });
        let executions = Arc::new(AtomicUsize::new(0));
        let queued_executions = executions.clone();
        let queued = queue.enqueue("video-proxy:queued".into(), 1, move |_canceled| {
            queued_executions.fetch_add(1, Ordering::SeqCst);
            Ok(Vec::new())
        });
        assert_eq!(queue.cancel(|key| key == "video-proxy:queued"), 1);
        assert!(queued.recv_timeout(Duration::from_secs(2)).expect("queued result").is_err());
        let _ = release_sender.send(());
        assert!(active.recv_timeout(Duration::from_secs(2)).expect("active result").is_ok());
        assert_eq!(executions.load(Ordering::SeqCst), 0);
    }
}
